### ISSUE TITLE
Removal of source files causes build errors.

### ISSUE THREAD

**Issue by axelrtgs** [maximkulkin/esp-http-parser#5]
Using Master building gives the following errors. Reverting one commit back solves the issue and builds fine. Looks like the removal of the source files creates issues.

/Users/{USER}/esp/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/homekit/libhomekit.a(server.c.obj):(.literal.homekit_server_on_url+0x30): undefined reference to `http_method_str'
/Users/{USER}/esp/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/homekit/libhomekit.a(server.c.obj):(.literal.client_context_new+0x0): undefined reference to `http_parser_init'
/Users/{USER}/esp/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/homekit/libhomekit.a(server.c.obj):(.literal.homekit_client_process+0x30): undefined reference to `http_parser_execute'
/Users/{USER}/esp/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/homekit/libhomekit.a(server.c.obj): in function `homekit_server_on_url':
/Users/{USER}/Documents/FanControl/build/../components/homekit/src/server.c:2903: undefined reference to `http_method_str'
/Users/{USER}/esp/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/homekit/libhomekit.a(server.c.obj): in function `client_context_new':
/Users/{USER}/Documents/FanControl/build/../components/homekit/src/server.c:335: undefined reference to `http_parser_init'
/Users/{USER}/esp/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/homekit/libhomekit.a(server.c.obj): in function `homekit_client_process':
/Users/{USER}/Documents/FanControl/build/../components/homekit/src/server.c:3038: undefined reference to `http_parser_execute'

**Comment by maximkulkin** [comment]
Just do `make clean` before building

**Comment by axelrtgs** [comment]
Thanks that fixed it. Appreciate the help.
